spring:
  application:
    name: api-gateway-scg1
  profiles:
    active:
      default

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - RewritePath=/api/*/(?<path>.*),/$\{path}
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: service1-A # 라우팅의 고유 ID (서비스의 ID가 아님)
          uri: lb://service1
          predicates:
            - Path=/api/service1/**
          filters:
            - RewritePath=/service1/(?<path>.*),/$\{path}
            - name: Service1Filter
              args:
                baseMessage: Spring Cloud Gateway Service1Filter
                preLogger: true
                postLogger: true
        - id: service2-A # 라우팅의 고유 ID (서비스의 ID가 아님)
          uri: lb://service2
          predicates:
            - Path=/api/service2/**
          filters:
            - RewritePath=/service2/(?<path>.*),/$\{path}
            - name: Service2Filter
              args:
                baseMessage: Spring Cloud Gateway Service2Filter
                preLogger: true
                postLogger: true


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 # Eureka Server 에 heartbeat 를 보내는 빈도를 나타내며 기본값은 30초
    lease-expiration-duration-in-seconds: 2 # Server 레지스트리에서 설정된 시간동안 heartbeat를 받지 못하면 해당 Eureka Instance를 Registry에서 제거 (기본 90초)
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5 # eureka에게 서비스 정보를 가져오는 주기
    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api2
  routes:
    service2: /srve2/**
